install.packages("checkpoint")
library("checkpoint")
checkpoint("2019-04-23")
install.packages("tidyverse")
install.packages('vctrs')
install.packages("widyr")
install.packages("igraph")
install.packages("gender")
install.packages("genderdata", repos = "http://packages.ropensci.org", type = "source")
install.packages('gridExtra')
install.packages('mgcv')
install.packages('SentimentAnalysis')
install.packages('wru')
install.packages('textcat')
