install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages("widyr")
install.packages("igraph")
install.packages("gender")
install.packages("genderdata", repos = "http://packages.ropensci.org", type = "source")
