#!/bin/bash
#PBS -q preempt -l nodes=24:ppn=5,vmem=31gb,walltime=170:00:00
#PBS -M yan30@iu.edu
#PBS -m abe
#PBS -N spark_yan
#PBS -V
#PBS -o pbs_stdout.txt
#PBS -e pbs_stderr.txt

cd $PBS_O_WORKDIR

SCRATCH="/N/dc2/projects/IUNI_MSAcademic"

WORKING_DIR="$SCRATCH/workingdir"

# Load module
module load java
module load hadoop
module load spark

source launch_spark_cluster_pbs --dir $WORKING_DIR

echo "spark master url $SPARK_URL"

sleep 10000m

stop_spark_cluster_pbs
